-- 코드를 입력하세요
-- 종류별로 즐겨찾기 수가 가장 많은 식당의
-- 음식 종류, ID, 식당 이름, 즐겨찾기 수
-- 종류 DESC

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM
(SELECT FOOD_TYPE, REST_NAME, FAVORITES, REST_ID, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS R_RANK
FROM REST_INFO) A
-- RANK 대신 ROW_NUMBER를 써서 동시 랭킹 순위는 제거하는 게 좋겠다.
WHERE R_RANK = '1'
ORDER BY FOOD_TYPE DESC;
  
