SELECT C1.CAR_ID, ROUND(AVG(C1.DAY_COUNT), 1) AS AVERAGE_DURATION
FROM
(SELECT CAR_ID, (DATEDIFF(DATE(END_DATE), DATE(START_DATE)) + 1) AS DAY_COUNT, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) C1
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;