WITH RECURSIVE Hours AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM Hours
    WHERE HOUR < 23
)

SELECT
    h.HOUR,
    IFNULL(a.COUNT, 0) AS COUNT
FROM Hours h
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) a ON h.HOUR = a.HOUR
ORDER BY h.HOUR;